config-git: move away from deprecated arg (#66)
### What code changed, and why?

```
 styra link config git 'git@github.com:StyraInc/expo-scan-repository.git'
```
needs to change to
```
 styra link config git --repository 'git@github.com:StyraInc/expo-scan-repository.git'
```

### Definition of done

When you run `Styra Link: Config Git` in VSCode, you no longer see the
error indicated—this is the old invocation (notice the git URL is NOT
preceded with `--repository`:
```
Spawning child process:
    project path: /Users/msorens/github/projects/_ms-demo-compliance-repo
    styra link config git 'git@github.com:StyraInc/expo-scan-repository.git' --branch master  --password-stdin --key-file '/Users/msorens/.ssh/id_rsa'
child process (styra) complete

ERROR: Warning: Use of the repository-url argument is deprecated and will be removed in a future version. Use the '--repository' flag instead.
```

### Related Resources

STY-16083